### PR TITLE
Update CODEOWNERS to current active devs

### PR DESCRIPTION
**Pull request by shravanhariharan2**
So that Sumeet and Michael no longer need to have their emails spammed and so that Marcelo starts getting his email spammed

image

### CODE REVIEW

**Review by farisashai — APPROVED** [review]
good idea 👍

**Comment by sumeet-bansal** [comment]
I have a filter lol, it is cool to see the updates though

**Comment by StormFireFox1** [comment]
The end of an era

**Comment by shravanhariharan2** [comment]
Going to add back in Sumeet and merge

**Pull request merged**
