### PR TITLE
Remove lastLogin column from Users table

### LINKED ISSUE #211: lastLogin column of "Users" table doesn't ever get updated
The `lastLogin` column of the "Users" table doesn't ever get updated because there's no writes to the column when a user logs in. I'm assuming that we'd want that functionality to exist in the `POST /auth/login` route, but maybe a broader discussion would be if we actually need this column or not. I'm not seeing any immediate benefits besides being able to manually audit user activity - @sumeet-bansal what are your thoughts on this?

### PR DESCRIPTION
**Pull request by shravanhariharan2**
Closes #211

### CODE REVIEW

**Review by dowhep — APPROVED** [review]
LGTM 🚀

**Review by meshachadoe — APPROVED** [review]
Looks good.

**Comment by farisashai** [comment]
@shravanhariharan2 Is this good to merge

**Comment by shravanhariharan2** [comment]
Holding off on merge until #226 is resolved, so that we can use this PR to test if automated migrations work.

**Pull request closed without merging**
