### PR TITLE
Implement GET /order/pickup/:uuid route and tests, plus modify order response schema

### LINKED ISSUE #233: Add GET '/order/pickup/:uuid'
Allow an admin to fetch the data for a pickup event, given its uuid.

### PR DESCRIPTION
**Pull request by shravanhariharan2**
Closes #233

### CODE REVIEW

**Comment by trulyronak** [comment]
will this give us the user's name?

For context this is what we're going to be using the route for

Screen Shot 2021-12-21 at 11 38 08 PM

**Comment by shravanhariharan2** [comment]
The current changes don't directly give the user name or item info - but here's an updated example response after I added those respective joins. This should give enough detail regarding the customer's user info and the items ordered:

```json
{
    "error": null,
    "order": {
        "uuid": "8a16b9ec-bbdb-401f-b843-914d6291598a",
        "user": {
            "uuid": "32198699-5897-4254-a898-3cd8dc9841d5",
            "firstName": "Shravan",
            "lastName": "Hariharan",
            "profilePicture": null,
            "graduationYear": 2024,
            "major": "Computer Science",
            "bio": null,
            "points": 50
        },
        "totalCost": 2700,
        "status": "PLACED",
        "orderedAt": "2021-12-27T02:25:57.297Z",
        "pickupEvent": {
            "uuid": "1ae7b408-2468-4fd2-93f7-ef111549aece",
            "title": "Merch Distribution @ Library Walk",
            "start": "2022-01-10T17:00:00.000Z",
            "end": "2022-01-10T18:00:00.000Z",
            "description": "Come through to Library Walk between 3-4pm to pickup your event and get free boba!",
            "orderLimit": 50
        },
        "items": [
            {
                "uuid": "92cbc579-95cd-4bff-8986-4fdf7770137c",
                "option": {
                    "uuid": "90302e8d-a39c-49a6-a07a-455fc5dcef69",
                    "price": 1500,
                    "discountPercentage": 15,
                    "metadata": {
                        "type": "SIZE",
                        "value": "2x2",
                        "position": 0
                    },
                    "item": {
                        "uuid": "c5e040a5-6c2f-4828-9925-dcfdba8db16b",
                        "itemName": "Hack School Sticker Pack (4) - Cyan",
                        "picture": "https://i.imgur.com/pSZ921P.png",
                        "description": "Make space on your laptop cover for these Cyan stickers. Pack of 4, size in inches."
                    }
                },
                "salePriceAtPurchase": 1275,
                "discountPercentageAtPurchase": 15,
                "fulfilled": false,
                "fulfilledAt": null,
                "notes": null
            },
            {
                "uuid": "d17518c8-7c3e-429e-b5a1-5fbaf07d5949",
                "option": {
                    "uuid": "08919a0c-0c71-4aee-8284-dd0b6f969a4f",
                    "price": 1500,
                    "discountPercentage": 5,
                    "metadata": {
                        "type": "SIZE",
                        "value": "3x3",
                        "position": 1
                    },
                    "item": {
                        "uuid": "c5e040a5-6c2f-4828-9925-dcfdba8db16b",
                        "itemName": "Hack School Sticker Pack (4) - Cyan",
                        "picture": "https://i.imgur.com/pSZ921P.png",
                        "description": "Make space on your laptop cover for these Cyan stickers. Pack of 4, size in inches."
                    }
                },
                "salePriceAtPurchase": 1425,
                "discountPercentageAtPurchase": 5,
                "fulfilled": false,
                "fulfilledAt": null,
                "notes": null
            }
        ]
    }
}
```

**Comment by shravanhariharan2** [comment]
@trulyronak @steets250 pinging for review so that yall are good with these changes (no need to look through things like the test code, just let me know if the joins make sense for the requested access patterns)

**Comment by steets250** [comment]
Seems good to me, esp based on the sample payload you gave, it seems like we have everything covered.

**Review by trulyronak — APPROVED** [review]
yep this is good for us in FE

**Pull request merged**
