### PR TITLE
Add email template for cancel all orders confirmation

### PR DESCRIPTION
**Pull request by shravanhariharan2**
Adds a new template to let members know that their order was cancelled second-hand because they didn't pick up their merchandise by the end of the quarter, since otherwise they might be confused why their order was suddenly cancelled.

Example email:
image

### CODE REVIEW

**Comment by shravanhariharan2** [comment]
@michl1001 thoughts on email wording as well?

**Comment by michl1001** [comment]
Might be good to say "recent quarter" rather than "past quarter" for clarity

**Comment by michl1001** [comment]
"You placed an order on...." might be clearer than "you had placed an order on..."

**Comment by michl1001** [comment]
This is definitely optional but we could have something like: "Let us know at [email here] if there are any issues!"

**Comment by shravanhariharan2** [comment]
> This is definitely optional but we could have something like: "Let us know at [email here] if there are any issues!"

Wasn't displayed in the picture I sent but we have this in the footer of the email already.

**Review by michl1001 — APPROVED** [review]
Looks good, but hard to really test from just looking - main worries include possible bugs with refunding system as it passes to the email but if it pasted prior tests, should be fine

**Pull request merged**
