### PR TITLE
Add get all emails admin route

### LINKED ISSUE #151: Add admin route for returning all portal user emails
Create a route for returning all portal user emails. Useful to frontend for creating auto-complete functionality for searching for users.

### PR DESCRIPTION
**Pull request by shravanhariharan2**
Closes #151

### CODE REVIEW

**Review by steets250 — APPROVED** [review]
Tested on Postman and works correctly.

**Review by sumeet-bansal — COMMENTED** [review]
LGTM but I think this endpoint might better fit in an `AdminController`. What do you think? Also can you bump the version?

**Comment by shravanhariharan2** [comment]
@sumeet-bansal my thinking was that the route name `/user/email` made more sense intuitively than something like `/admin/email`, and the functionality like viewing members emails (with potential suborg filters after user roles are implemented) could be useful for future roles other than just admins.

Also, do we want to return all members emails, or only return those emails where `user.state !== BLOCKED`? And similar question for milestones, since right now it can grant all users points, even potentially blocked ones.

**Comment by sumeet-bansal** [comment]
I think of the user controller as anything that's got to do with specific accounts, like getting/updating a profile, so getting all emails doesn't really fit into that since it's more of an admin action.

**Comment by sumeet-bansal** [comment]
As for returning blocked emails, I think this would be used for accounts in good standing but I also don't know enough to speculate on how the route might be used. Maybe let FE filter to whatever it wants? Or for now, default to excluding blocked users.

**Comment by shravanhariharan2** [comment]
@steets250 any preferences for returning all emails vs only emails "in good standing" (i.e. where `UserStatus !== BLOCKED` ?

Also, do we want to implement a way for blocking members in the portal anytime soon? Blocked status currently exists in the BE but there's no actual functionality for blocking users.

**Comment by steets250** [comment]
Returning every user regardless of status should be fine. The goal was to make it easier to award bonus points by allowing an admin to search from a drop down rather than typing them in and having email matching issues. I don't think a member who has a blocked status is likely to be rewarded bonus points, but that decision should be left up to Casey or the membership team.

**Comment by shravanhariharan2** [comment]
@sumeet-bansal @michl1001 ready for review (can't re-request while awaiting previous request)

**Review by sumeet-bansal — APPROVED** [review]

**Pull request merged**
