### PR TITLE
Refactor repository parameters to single types 

### LINKED ISSUE #167: Refactor repository parameters
Now that we have some internal types made for batch routes, we should explore refactoring many of the repository methods with high parameter counts to use internal types to reduce the number of params passed

### PR DESCRIPTION
**Pull request by shravanhariharan2**
Closes #167

### CODE REVIEW

**Comment by shravanhariharan2** [comment]
@sumeet-bansal @michl1001 I just started with the activity repository change that we discussed [here](https://github.com/acmucsd/membership-portal/pull/165#issuecomment-794565431) but I'm noticing that there's a bit of duplication that emerges, since the creation of the activity object is pushed up to the service level so a bunch of services need to create the object themselves now.

Not sure if we want to continue refactoring params or not since this would likely be the case for the rest after refactoring the other repository methods so I'd like to hear both your thoughts on it

**Comment by sumeet-bansal** [comment]
Can you give an example?

**Comment by shravanhariharan2** [comment]
I think it's more the fact that every 1 line of `logActivity()` that used to exist is now replaced with 3-4 lines since the object now is passed in for every call to `logActivity()` (for example,  [here](https://github.com/acmucsd/membership-portal/blob/884899249fe4de4fb4f4a420848bb58330747e9c/services/AttendanceService.ts#L57), [here](https://github.com/acmucsd/membership-portal/blob/884899249fe4de4fb4f4a420848bb58330747e9c/services/AttendanceService.ts#L151), and [here](https://github.com/acmucsd/membership-portal/blob/884899249fe4de4fb4f4a420848bb58330747e9c/services/MerchStoreService.ts#L272) ), so it feels a bit longer/more verbose. But I do like that now the activity fields are explicitly there (which make it easier to see what's being passed in) instead of having to guess what field is being passed based on its order in the parameter list / its type.

**Comment by sumeet-bansal** [comment]
Oh that's fine. Like you said, it's easier to see what's being passed in.

**Review by sumeet-bansal — APPROVED** [review]
LGTM. Nits:
+ Might as well inline the activity types instead of doing `type: activityType`.
+ If `pointsEarned: 0` can we just not include that in the object? We do that elsewhere and it should just default to 0.

**Comment by shravanhariharan2** [comment]
@sumeet-bansal are we doing patch bumps for refactors like this? Or should they be a minor bump like features? I recall you mentioning earlier that we can add more detail in the auto comment bot about this and I don't think I responded there, but yeah that would be great.

**Comment by shravanhariharan2** [comment]
re: inlining activity types- for more complex types that are dependent on things like `attendedAsStaff`, I think it's better to not inline since that's what we're doing with `pointsEarned` for those cases too. I'll change the ones that can only hold 1 value to be inline

**Comment by sumeet-bansal** [comment]
> @sumeet-bansal are we doing patch bumps for refactors like this? Or should they be a minor bump like features? I recall you mentioning earlier that we can add more detail in the auto comment bot about this and I don't think I responded there, but yeah that would be great.

Don't need to bump versions for refactors. I'll update the auto-comment bot.

**Comment by sumeet-bansal** [comment]
> re: inlining activity types- for more complex types that are dependent on things like `attendedAsStaff`, I think it's better to not inline since that's what we're doing with `pointsEarned` for those cases too. I'll change the ones that can only hold 1 value to be inline

`pointsEarned` shouldn't be inlined since it needs to be reused for creating attendance and adding points, but activity type is never reused and can be inlined.

**Pull request merged**
