### PR TITLE
Remove References to Activity.public for Milestones + Bonuses

### PR DESCRIPTION
**Pull request by shravanhariharan2**
Removed some more references to public column in ActivityRepository for milestones + bonuses

### CODE REVIEW

**Comment by shravanhariharan2** [comment]
I'm going to force-merge this since it's a hotfix that is currently blocking census rewards for membership. I'll create a separate PR addressing all the other changes mentioned in #143 for the public -> scope activity change.

**Comment by sumeet-bansal** [comment]
Are there any mislabeled Activity rows that need to be fixed in the database?

**Comment by shravanhariharan2** [comment]
@sumeet-bansal If you mean for entries in the scope column, then no there shouldn't be. This query initially would error out so nothing would get written, and the other activity queries properly scope them as `PUBLIC` or `HIDDEN`.

**Comment by sumeet-bansal** [comment]
Not incorrect scope, incorrect type, so bonus points mislabeled as milestones.

**Comment by shravanhariharan2** [comment]
Oh no that was an issue within this PR from the first commit. There was no labeling at all before this PR, it was just wrongly using `public` instead of `scope`

**Pull request merged**
