### PR TITLE
Add Steven Steiner to testing database seeds

### PR DESCRIPTION
**Pull request by StormFireFox1**
@steets250 should be a test account, Portal Lead ftw.

### CODE REVIEW

**Comment by sumeet-bansal** [comment]
I haven't touched it in a few months but I have a branch `seeds` where I was creating a bunch of new users/events/attendances for testing. If this PR isn't urgent I can finish those changes tonight, it's just a matter of wiring up all the attendances.

**Review by shravanhariharan2 — APPROVED** [review]

**Review by sumeet-bansal — APPROVED** [review]

**Comment by shravanhariharan2** [comment]
@sumeet-bansal this PR isn't urgent- Steven just wanted to test a cron job for the testing db and I'm sure that doesn't need to happen today, so we can just roll with your changes

**Comment by sumeet-bansal** [comment]
Sound good, I'll close this for now then.

**Comment by sumeet-bansal** [comment]
Following up, created the PR (#163).

**Pull request closed without merging**
